service: api

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  getSummonerData:
    handler: summoner/getSummoner.get
    events:
      - http:
          path: summoner/{summonerName}
          method: get
